In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



In [2]:
from sklearn.datasets import make_classification

In [3]:
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2,random_state=42)

In [4]:
pd.DataFrame(X).head()

0         1         2         3         4         5         6   \
0 -0.669356 -1.495778 -0.870766  1.141831  0.021606  1.730630 -1.251698   
1  0.093372  0.785848  0.105754  1.272354 -0.846316 -0.979093  1.263707   
2 -0.905797 -0.608341  0.295141  0.943716  0.092936  1.370397 -0.064772   
3 -0.585793  0.389279  0.698816  0.436236 -0.315082  0.459505  1.448820   
4  1.146441  0.515579 -1.222895 -0.396230 -1.293508 -0.352428  0.071254   

         7         8         9         10        11        12        13  \
0  0.289305  0.357163 -0.196811  0.829274  0.154850 -0.219970 -0.739137   
1  0.264020  2.411677 -0.960046  0.543479  0.199810  0.288724  0.732492   
2  0.287273 -0.533004 -0.032504 -0.549925 -0.510064 -0.868768 -0.598279   
3  0.505558 -1.440982 -1.134020 -0.241431  1.466783  0.678728 -1.190917   
4  1.239584  1.007133 -1.479444 -0.695695 -0.918127  0.604121  1.068379   

         14        15        16        17        18        19  
0  1.802012  1.634606 -0.938180 -1.267337 -1.276334  1.016643  
1 -0.872002 -1.654887 -1.130204 -0.122709  0.693431  0.911363  
2  0.019832  0.613460 -1.779439  0.830498 -0.737332 -0.578212  
3 -1.442381 -0.929136 -0.221600 -0.346772  0.034246 -1.040199  
4 -0.882271  2.303639 -0.973379  1.259233  0.360015  1.920368

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
from sklearn.linear_model import LogisticRegression
logestic = LogisticRegression()



In [6]:
logestic.fit(X_train, y_train)


LogisticRegression()

In [7]:
y_pred = logestic.predict(X_test)
print(y_pred)

[1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 0 0 0
 0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 1 1 1 0 0 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0
 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 0 0 0 0
 0 0 1 0 1 1 0 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0
 0 1 1 1 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 1 1 0 0 1
 1 0 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 0 1 0 1 0 1 0 0 0
 0 0 0 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 0 1 0 1 0 0 0 0 1 0 0 1 1 1 0 0
 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 1 0 1 1 0
 0 1 0 0]


In [8]:
logestic.predict_proba(X_test)

array([[3.90463328e-01, 6.09536672e-01],
       [1.31070740e-01, 8.68929260e-01],
       [4.86090535e-01, 5.13909465e-01],
       [2.20910617e-01, 7.79089383e-01],
       [4.62763436e-02, 9.53723656e-01],
       [9.47654807e-01, 5.23451932e-02],
       [7.72363239e-01, 2.27636761e-01],
       [2.10652946e-01, 7.89347054e-01],
       [2.62962545e-01, 7.37037455e-01],
       [6.87582346e-01, 3.12417654e-01],
       [3.35752421e-02, 9.66424758e-01],
       [3.29170508e-01, 6.70829492e-01],
       [9.95910519e-01, 4.08948143e-03],
       [5.00693064e-01, 4.99306936e-01],
       [2.80327289e-01, 7.19672711e-01],
       [8.20394408e-01, 1.79605592e-01],
       [9.35541003e-01, 6.44589971e-02],
       [4.87080427e-02, 9.51291957e-01],
       [1.12369089e-01, 8.87630911e-01],
       [5.21312907e-01, 4.78687093e-01],
       [5.65232790e-03, 9.94347672e-01],
       [7.44918172e-01, 2.55081828e-01],
       [9.48559833e-01, 5.14401674e-02],
       [8.97235307e-01, 1.02764693e-01],
       [2.130755

In [9]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report



In [10]:
score = accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))





0.85
[[127  18]
 [ 27 128]]
              precision    recall  f1-score   support

           0       0.82      0.88      0.85       145
           1       0.88      0.83      0.85       155

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



### Hyperparameteter tunning

In [11]:
# from sklearn.linear_model import LogisticRegression
# model = LogisticRegression()
# 
# penalty = ['l1','l2']
# c_values = [100,10,1.0,0.1,0.01]
# solver = ['newton-cg','lbfgs','liblinear','sag','saga']

In [12]:
# params = dict(panalty=penalty,C=c_values,solver=solver)
# params

In [13]:
from sklearn.model_selection import GridSearchCV, StratifiedGroupKFold
# cv = StratifiedGroupKFold()
# grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv)




In [14]:
# grid

In [15]:
# grid.fit(X_train,y_train)

In [16]:
param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2'],     # ✅ correct spelling
    'solver': ['liblinear']      # solver compatible with l1 and l2
}

log_reg = LogisticRegression()
grid = GridSearchCV(log_reg, param_grid, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best Score:", grid.best_score_)


Best Parameters: {'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}
Best Score: 0.8814285714285713


In [17]:
y_pred = grid.predict(X_test)


In [18]:
score = accuracy_score(y_test,y_pred)
print(score)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.8466666666666667
              precision    recall  f1-score   support

           0       0.82      0.88      0.85       145
           1       0.88      0.81      0.85       155

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

[[128  17]
 [ 29 126]]
